name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-11-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip \
            curl \
            cython3  # إضافة Cython من apt

    - name: Install Python dependencies
      run: |
        pip install --user --upgrade pip
        pip install --user buildozer==1.5.0
        pip install --user cython  # تثبيت Cython عبر pip
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Prepare Python-for-Android
      run: |
        rm -rf .buildozer || true
        mkdir -p .buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android

    - name: Build APK
      run: |
        buildozer -v android debug
