name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install buildozer cython==0.29.33 virtualenv

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
          ls bin/  # تأكد من وجود APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: mykivyapp-debug.apk
          path: bin/*.apk  # سيحمل كل APKs في مجلد bin/
