name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-11-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip \
            curl

    - name: Install Buildozer
      run: |
        pip install --user buildozer==1.5.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Initialize Buildozer environment
      run: |
        buildozer android clean
        rm -rf .buildozer || true
        buildozer android init

    - name: Manually setup python-for-android
      run: |
        mkdir -p .buildozer/android/platform
        git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android

    - name: Build APK
      run: |
        buildozer -v android debug
