name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip \
            curl \
            cython3 \
            wget

    - name: Setup Android SDK/NDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd-tools.zip
        unzip cmd-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d ndk-temp
        mkdir -p $HOME/android-sdk/ndk/25b
        mv ndk-temp/android-ndk-r25b/* $HOME/android-sdk/ndk/25b
        rm -rf ndk-temp android-ndk-r25b-linux.zip

    - name: Install Buildozer
      run: |
        pip install --user buildozer==1.5.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Clone python-for-android
      run: |
        mkdir -p .buildozer/android/platform
        git clone --depth 1 --branch 2023.08.25 \
          https://github.com/kivy/python-for-android \
          .buildozer/android/platform/python-for-android

    - name: Configure Build Environment
      run: |
        if [ ! -f buildozer.spec ]; then
            buildozer init
        fi
        
        echo -e "\n[buildozer]" >> buildozer.spec
        echo "p4a.branch = 2023.08.25" >> buildozer.spec
        echo "android.ndk_path = $HOME/android-sdk/ndk/25b" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug 2>&1 | tee build.log

        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "✅ Build succeeded!"
        else
          echo "❌ Build failed!"
          cat build.log
          exit 1
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-Output
        path: |
          bin/*.apk
          build.log
