name: Buildozer Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libncurses6 \
          libffi-dev \
          libssl-dev \
          python3-pip \
          python3-setuptools \
          openjdk-11-jdk \
          unzip \
          zip \
          zlib1g-dev \
          liblzma-dev \
          libbz2-dev \
          libsqlite3-dev \
          libreadline-dev \
          libjpeg-dev \
          libfreetype6-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libglu1-mesa-dev \
          libglfw3 \
          libglfw3-dev

        pip install --upgrade pip
        pip install cython buildozer

    - name: Manually install Android NDK (fix for urlretrieve error)
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O ndk.zip
        unzip -q ndk.zip
        rm ndk.zip

    - name: Set NDK path in buildozer.spec
      run: |
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r23b" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
