name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-11-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip

    - name: Install Buildozer
      run: |
        pip install --user buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Force recreate directories
      run: |
        buildozer android clean
        rm -rf .buildozer  # حذف المجلد القديم
        buildozer android init  # إعادة تهيئة المشروع

    - name: Build APK
      run: |
        buildozer -v android debug
