name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          openjdk-11-jdk \
          python3-pip \
          zlib1g-dev \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer
      run: |
        pip install --user buildozer

    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug
        
        if ! ls bin/*.apk 1> /dev/null 2>&1; then
          echo "Error: APK not found!"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: evilapp-apk
        path: bin/*.apk
