name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Ubuntu mirrors
      run: |
        sudo sed -i 's|http://archive.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system tools
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          software-properties-common \
          ca-certificates \
          curl \
          gnupg

    - name: Add Android repository
      run: |
        curl -fsSL https://dl.google.com/android/repository/archive-key.asc | sudo gpg --dearmor -o /usr/share/keyrings/android-archive.gpg
        echo "deb [signed-by=/usr/share/keyrings/android-archive.gpg arch=amd64] https://dl.google.com/android/repository/ stable main" | sudo tee /etc/apt/sources.list.d/android-google.list
        sudo apt-get update -y

    - name: Install core dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          openjdk-17-jdk \
          python3-pip \
          build-essential

    - name: Install Buildozer
      run: |
        pip install --user buildozer==1.5.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Prepare build environment
      run: |
        buildozer android init || true
        mkdir -p .buildozer/android/platform

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Release
        path: bin/*.apk
