name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config wget
          pip install --upgrade pip setuptools wheel
          pip install cython virtualenv buildozer

          # Download Android Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/cmdline-tools

          # Set up cmdline-tools directory
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest

          # Accept licenses and install components
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-30" \
            "build-tools;33.0.2"

          # Set local SDK path for Buildozer
          echo "[app]" > buildozer.spec
          echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: bin/*.apk
