name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROID_HOME:     $HOME/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python & Buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config wget tar
        pip install --upgrade pip setuptools wheel
        pip install --user cython virtualenv buildozer
        export PATH=$HOME/.local/bin:$PATH

    - name: Install Android command-line tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        yes | latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

    - name: Install platform-tools, build-tools & NDK
      run: |
        latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        # هنا نثبت NDK إصدار مدعوم
        latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "ndk;21.4.7075529"

    - name: Configure buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = InstaDZ
        package.name = instadz
        package.domain = org.instadz
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0
        requirements = python3,kivy
        orientation = portrait
        fullscreen = 1
        android.permissions = INTERNET
        android.api = 30
        android.minapi = 21
        android.build_tools_version = 30.0.3
        android.ndk = 21.4.7075529

        [buildozer]
        log_level = 2
        warn_on_root = 0
        android.sdk_path = $ANDROID_SDK_ROOT
        EOF

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: instadz-debug
        path: bin/*.apk
