name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip \
            curl \
            cython3

    - name: Install Buildozer with dependencies
      run: |
        pip install --user --upgrade pip wheel
        pip install --user buildozer==1.5.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Initialize Buildozer
      run: |
        mkdir -p ~/.buildozer
        echo "[buildozer]" > ~/.buildozer/default.cfg
        echo "log_level = 2" >> ~/.buildozer/default.cfg
        buildozer init

    - name: Build with debug logs
      run: |
        buildozer android clean
        buildozer -v android debug > build.log 2>&1 || (cat build.log && exit 1)
        cat build.log

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: App-Release
        path: bin/*.apk

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Build-Logs
        path: build.log
