name: Build InstaDZ APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          git \
          openjdk-17-jdk \  # تم الترقية إلى JDK 17
          python3-pip \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          android-sdk \  # إضافة حزمة Android SDK الأساسية
          android-sdk-build-tools-34 \  # إصدار مستقر
          android-sdk-platform-tools

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
        
        # تثبيت إصدار محدد من Build-Tools يتضمن AIDL
        sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

        # إنشاء روابط رمزية للأدوات المطلوبة
        ln -s ~/Android/Sdk/build-tools/34.0.0/aidl /usr/local/bin/aidl
        ln -s ~/Android/Sdk/build-tools/34.0.0/* /usr/local/bin/

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Build APK
      run: |
        export PATH=$PATH:~/Android/Sdk/build-tools/34.0.0:~/.local/bin
        export ANDROID_SDK_ROOT=~/Android/Sdk
        
        buildozer -v android debug
        
        if ! ls bin/*.apk 1> /dev/null 2>&1; then
          echo "Error: APK not generated!"
          cat .buildozer/android/platform/build/build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: instadz-apk
        path: bin/*.apk
        retention-days: 5
