name: Build APK with Buildozer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # زيادة وقت التنفيذ

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Buildozer dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.android
          ~/.cache/pip
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          openjdk-11-jdk \
          python3-pip \
          python3-setuptools \
          unzip \
          zip \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          libncurses6 \
          libjpeg-dev \
          libfreetype6-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user buildozer cython virtualenv

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        cd ~/.buildozer/android/platform
        
        # Download command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d cmdline-tools-tmp
        mv cmdline-tools-tmp/cmdline-tools android-sdk/cmdline-tools/latest
        rm -rf cmdline-tools-tmp cmdline-tools.zip
        
        # Accept licenses
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # Install required SDK components
        android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Setup Android NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Download NDK (Recommended version)
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
        unzip -q ndk.zip
        rm ndk.zip

    - name: Configure environment
      run: |
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Configure Buildozer
      run: |
        echo "[app]" > buildozer.spec
        echo "title = MyApp" >> buildozer.spec
        echo "package.name = myapp" >> buildozer.spec
        echo "package.domain = org.test" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "version = 0.1" >> buildozer.spec
        echo "requirements = python3,kivy" >> buildozer.spec
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> buildozer.spec
        echo "android.sdk_path = $HOME/.buildozer/android/platform/android-sdk" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 33" >> buildozer.spec

    - name: Build APK with retry
      run: |
        export PATH=$PATH:~/.local/bin:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
        
        for i in {1..3}; do
          buildozer android clean && \
          buildozer android debug && break
          echo "Build attempt $i failed, retrying..."
          sleep 10
        done

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
        retention-days: 5

    - name: Check build logs if failed
      if: failure()
      run: |
        cat .buildozer/android/platform/build/build.log
