name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git python3-pip \
            libgl1-mesa-dev libgles2-mesa-dev \
            build-essential autoconf \
            libtool pkg-config \
            zlib1g-dev libncurses5-dev libffi-dev \
            libsqlite3-dev libssl-dev \
            libjpeg-dev libfreetype6-dev \
            liblcms2-dev libwebp-dev libharfbuzz-dev \
            libfribidi-dev libxcb1-dev \
            openjdk-17-jdk

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer -v android debug
