name: Build EvilApp APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk python3-dev python3-pip git unzip
        pip install --upgrade pip
        pip install buildozer kivy==2.1.0 cython==0.29.24 pyjnius

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/cmdline-tools/bin
        yes | sdkmanager --sdk_root=$ANDROID_HOME"platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: evilapp-apk
        path: bin/*.apk
