name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/build-tools/33.0.2:${PATH}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libncurses5 libstdc++6 git autoconf libtool pkg-config
          pip install --upgrade pip
          pip install Cython virtualenv buildozer

      - name: Install Android SDK
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          sudo chown $USER:$USER -R /opt/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d /opt/android-sdk/cmdline-tools
          mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;33.0.2"

      - name: Set sdk path in buildozer.spec
        run: |
          if ! grep -q "android.sdk_path" buildozer.spec; then
            echo -e "\n[app]\nandroid.sdk_path = /opt/android-sdk" >> buildozer.spec
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app-debug
          path: bin/*.apk
