name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git libncurses5 libffi-dev libssl-dev libsqlite3-dev

    - name: Upgrade pip and install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython virtualenv appdirs

    - name: Install buildozer
      run: |
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: built-apk
        path: bin/*.apk
