name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3-pip \
            build-essential \
            openjdk-17-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            git \
            unzip \
            curl \
            cython3 \
            wget

    - name: Install Android tools
      run: |
        # إنشاء مجلد SDK مع صلاحيات المستخدم
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        # تنزيل وتثبيت أدوات سطر الأوامر
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd-tools.zip
        unzip cmd-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        # إعداد متغيرات البيئة
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        
        # قبول التراخيص وتثبيت المكونات
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        
        # تنزيل NDK 25b مباشرةً
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        mv android-ndk-r25b ndk/25b

    - name: Install Buildozer
      run: |
        pip install --user buildozer==1.5.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Buildozer
      run: |
        mkdir -p ~/.buildozer
        echo "[buildozer]" > ~/.buildozer/default.cfg
        echo "android.ndk_path = $HOME/android-sdk/ndk/25b" >> ~/.buildozer/default.cfg
        echo "android.sdk_path = $HOME/android-sdk" >> ~/.buildozer/default.cfg

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug 2>&1 | tee build.log
        
        if [ -f bin/*.apk ]; then
          echo "✅ Build succeeded!"
        else
          echo "❌ Build failed!"
          cat build.log
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
