name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            zlib1g-dev \
            openjdk-17-jdk \
            libffi-dev \
            libssl-dev

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK (Skip init)
      run: |
        buildozer -v android debug  # لا تستخدم buildozer init

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
