name: Build InstaDZ APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          git \
          openjdk-17-jdk \
          python3-pip \
          zlib1g-dev \
          libffi-dev \
          libssl-dev \
          unzip

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk
        cd ~/.buildozer/android/platform
        
        # Download and install cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d cmdline-tools-tmp
        mv cmdline-tools-tmp/cmdline-tools android-sdk/cmdline-tools/latest
        rm -rf cmdline-tools-tmp cmdline-tools.zip
        
        # Set PATH for sdkmanager
        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
        # Accept licenses and install components
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        
        # Verify installation
        ls -la $HOME/.buildozer/android/platform/android-sdk

    - name: Setup Android NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
        unzip -q ndk.zip
        rm ndk.zip

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Build APK
      run: |
        export PATH=$PATH:$HOME/.local/bin:$HOME/.buildozer/android/platform/android-sdk/platform-tools
        buildozer -v android debug
        
        if ! ls bin/*.apk 1> /dev/null 2>&1; then
          echo "Error: APK not generated!"
          cat .buildozer/android/platform/build/build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: instadz-apk
        path: bin/*.apk
        retention-days: 5
